// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Recetarion.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(RecetarionDbContext))]
    [Migration("20230822081712_TablesUpdate")]
    partial class TablesUpdate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("GroupUser", b =>
                {
                    b.Property<Guid>("GroupsId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("UsersId")
                        .HasColumnType("char(36)");

                    b.HasKey("GroupsId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("GroupUser");
                });

            modelBuilder.Entity("IngredientRecipe", b =>
                {
                    b.Property<Guid>("IngredientsId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("RecipesId")
                        .HasColumnType("char(36)");

                    b.HasKey("IngredientsId", "RecipesId");

                    b.HasIndex("RecipesId");

                    b.ToTable("IngredientRecipe");
                });

            modelBuilder.Entity("PublicationUser", b =>
                {
                    b.Property<Guid>("PublicationsId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("UsersLikeId")
                        .HasColumnType("char(36)");

                    b.HasKey("PublicationsId", "UsersLikeId");

                    b.HasIndex("UsersLikeId");

                    b.ToTable("PublicationUser");
                });

            modelBuilder.Entity("Recetarion.Models.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnOrder(0);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid?>("ImageId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("PublicationId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<string>("UserPermissionAction")
                        .HasColumnType("varchar(255)");

                    b.Property<Guid?>("UserPermissionUserRolesId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("PublicationId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserPermissionUserRolesId", "UserPermissionAction");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("Recetarion.Models.Critic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnOrder(0);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("PublicationId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.ToTable("Critics");
                });

            modelBuilder.Entity("Recetarion.Models.CustomList", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnOrder(0);

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<string>("UserPermissionAction")
                        .HasColumnType("varchar(255)");

                    b.Property<Guid?>("UserPermissionUserRolesId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("UserPermissionUserRolesId", "UserPermissionAction");

                    b.ToTable("CustomLists");
                });

            modelBuilder.Entity("Recetarion.Models.CustomListRecipe", b =>
                {
                    b.Property<Guid>("CustomListId")
                        .HasColumnType("char(36)")
                        .HasColumnOrder(0);

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("char(36)")
                        .HasColumnOrder(1);

                    b.HasKey("CustomListId", "RecipeId");

                    b.HasIndex("RecipeId");

                    b.ToTable("CustomListRecipes");
                });

            modelBuilder.Entity("Recetarion.Models.Follow", b =>
                {
                    b.Property<Guid>("FollowerId")
                        .HasColumnType("char(36)")
                        .HasColumnOrder(0);

                    b.Property<Guid>("FolloweeId")
                        .HasColumnType("char(36)")
                        .HasColumnOrder(1);

                    b.HasKey("FollowerId", "FolloweeId");

                    b.HasIndex("FolloweeId");

                    b.ToTable("Follows");
                });

            modelBuilder.Entity("Recetarion.Models.Group", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnOrder(0);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("ImageId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UserPermissionAction")
                        .HasColumnType("varchar(255)");

                    b.Property<Guid?>("UserPermissionUserRolesId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserPermissionUserRolesId", "UserPermissionAction");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("Recetarion.Models.GroupPermission", b =>
                {
                    b.Property<Guid>("GroupRoleId")
                        .HasColumnType("char(36)")
                        .HasColumnOrder(0);

                    b.Property<string>("Action")
                        .HasColumnType("varchar(255)")
                        .HasColumnOrder(1);

                    b.HasKey("GroupRoleId", "Action");

                    b.ToTable("GroupPermissions");
                });

            modelBuilder.Entity("Recetarion.Models.GroupRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnOrder(0);

                    b.Property<Guid>("GroupId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("GroupRoles");
                });

            modelBuilder.Entity("Recetarion.Models.Image", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnOrder(0);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<Guid?>("PublicationId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("PublicationId");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("Recetarion.Models.Ingredient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnOrder(0);

                    b.Property<int>("Calories")
                        .HasColumnType("int");

                    b.Property<float>("Density")
                        .HasColumnType("float");

                    b.Property<Guid>("ImageId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(32)");

                    b.Property<string>("UserPermissionAction")
                        .HasColumnType("varchar(255)");

                    b.Property<Guid?>("UserPermissionUserRolesId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserPermissionUserRolesId", "UserPermissionAction");

                    b.ToTable("Ingredients");
                });

            modelBuilder.Entity("Recetarion.Models.LikeIngredient", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)")
                        .HasColumnOrder(0);

                    b.Property<Guid>("IngredientId")
                        .HasColumnType("char(36)")
                        .HasColumnOrder(1);

                    b.Property<bool>("IsDislike")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserPermissionAction")
                        .HasColumnType("varchar(255)");

                    b.Property<Guid?>("UserPermissionUserRolesId")
                        .HasColumnType("char(36)");

                    b.HasKey("UserId", "IngredientId");

                    b.HasIndex("IngredientId");

                    b.HasIndex("UserPermissionUserRolesId", "UserPermissionAction");

                    b.ToTable("LikeIngredients");
                });

            modelBuilder.Entity("Recetarion.Models.LikePublication", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)")
                        .HasColumnOrder(0);

                    b.Property<Guid>("PublicationId")
                        .HasColumnType("char(36)")
                        .HasColumnOrder(1);

                    b.Property<string>("UserPermissionAction")
                        .HasColumnType("varchar(255)");

                    b.Property<Guid?>("UserPermissionUserRolesId")
                        .HasColumnType("char(36)");

                    b.HasKey("UserId", "PublicationId");

                    b.HasIndex("PublicationId");

                    b.HasIndex("UserPermissionUserRolesId", "UserPermissionAction");

                    b.ToTable("LikePublications");
                });

            modelBuilder.Entity("Recetarion.Models.Publication", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnOrder(0);

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<string>("UserPermissionAction")
                        .HasColumnType("varchar(255)");

                    b.Property<Guid?>("UserPermissionUserRolesId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserPermissionUserRolesId", "UserPermissionAction");

                    b.ToTable("Publications");
                });

            modelBuilder.Entity("Recetarion.Models.PublicationImage", b =>
                {
                    b.Property<Guid>("PublicationId")
                        .HasColumnType("char(36)")
                        .HasColumnOrder(0);

                    b.Property<Guid>("ImageId")
                        .HasColumnType("char(36)")
                        .HasColumnOrder(1);

                    b.Property<uint>("Order")
                        .HasColumnType("int unsigned");

                    b.HasKey("PublicationId", "ImageId");

                    b.ToTable("PublicationImages");
                });

            modelBuilder.Entity("Recetarion.Models.Recipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnOrder(0);

                    b.Property<Guid?>("CustomListId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("PublicationId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("CustomListId");

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("Recetarion.Models.RecipeIngredient", b =>
                {
                    b.Property<Guid>("RecipeId")
                        .HasColumnType("char(36)")
                        .HasColumnOrder(0);

                    b.Property<Guid>("IngredientId")
                        .HasColumnType("char(36)")
                        .HasColumnOrder(1);

                    b.Property<Guid>("UnitId")
                        .HasColumnType("char(36)");

                    b.Property<uint>("quantity")
                        .HasColumnType("int unsigned");

                    b.HasKey("RecipeId", "IngredientId");

                    b.HasIndex("IngredientId");

                    b.ToTable("RecipeIngredients");
                });

            modelBuilder.Entity("Recetarion.Models.Step", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnOrder(0);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("ImageId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.ToTable("Steps");
                });

            modelBuilder.Entity("Recetarion.Models.Subscription", b =>
                {
                    b.Property<Guid>("GroupId")
                        .HasColumnType("char(36)")
                        .HasColumnOrder(0);

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("char(36)");

                    b.Property<string>("UserPermissionAction")
                        .HasColumnType("varchar(255)");

                    b.Property<Guid?>("UserPermissionUserRolesId")
                        .HasColumnType("char(36)");

                    b.HasKey("GroupId", "UserId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserPermissionUserRolesId", "UserPermissionAction");

                    b.ToTable("Subscriptions");
                });

            modelBuilder.Entity("Recetarion.Models.Unit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnOrder(0);

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasColumnType("varchar(32)");

                    b.Property<bool>("Default")
                        .HasColumnType("tinyint(1)");

                    b.Property<float>("Equivalence")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(32)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("varchar(32)");

                    b.HasKey("Id");

                    b.ToTable("Units");
                });

            modelBuilder.Entity("Recetarion.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnOrder(0);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<uint>("FollowerCount")
                        .HasColumnType("int unsigned");

                    b.Property<Guid>("ImageId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("IngredientId")
                        .HasColumnType("char(36)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("TokenFacebook")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("TokenTwitter")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UserRoleId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("IngredientId");

                    b.HasIndex("UserRoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Recetarion.Models.UserPermission", b =>
                {
                    b.Property<Guid>("UserRolesId")
                        .HasColumnType("char(36)")
                        .HasColumnOrder(0);

                    b.Property<string>("Action")
                        .HasColumnType("varchar(255)")
                        .HasColumnOrder(1);

                    b.Property<Guid?>("UserRoleId")
                        .HasColumnType("char(36)");

                    b.HasKey("UserRolesId", "Action");

                    b.HasIndex("UserRoleId");

                    b.ToTable("UserPermissions");
                });

            modelBuilder.Entity("Recetarion.Models.UserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnOrder(0);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(32)");

                    b.HasKey("Id");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("GroupUser", b =>
                {
                    b.HasOne("Recetarion.Models.Group", null)
                        .WithMany()
                        .HasForeignKey("GroupsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Recetarion.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("IngredientRecipe", b =>
                {
                    b.HasOne("Recetarion.Models.Ingredient", null)
                        .WithMany()
                        .HasForeignKey("IngredientsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Recetarion.Models.Recipe", null)
                        .WithMany()
                        .HasForeignKey("RecipesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PublicationUser", b =>
                {
                    b.HasOne("Recetarion.Models.Publication", null)
                        .WithMany()
                        .HasForeignKey("PublicationsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Recetarion.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UsersLikeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Recetarion.Models.Comment", b =>
                {
                    b.HasOne("Recetarion.Models.Publication", null)
                        .WithMany("Comments")
                        .HasForeignKey("PublicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Recetarion.Models.User", null)
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Recetarion.Models.UserPermission", null)
                        .WithMany("Comments")
                        .HasForeignKey("UserPermissionUserRolesId", "UserPermissionAction");
                });

            modelBuilder.Entity("Recetarion.Models.Critic", b =>
                {
                    b.HasOne("Recetarion.Models.Recipe", null)
                        .WithMany("Critics")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Recetarion.Models.CustomList", b =>
                {
                    b.HasOne("Recetarion.Models.User", null)
                        .WithMany("Lists")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Recetarion.Models.UserPermission", null)
                        .WithMany("Lists")
                        .HasForeignKey("UserPermissionUserRolesId", "UserPermissionAction");
                });

            modelBuilder.Entity("Recetarion.Models.CustomListRecipe", b =>
                {
                    b.HasOne("Recetarion.Models.CustomList", null)
                        .WithMany("RecipesPivot")
                        .HasForeignKey("CustomListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Recetarion.Models.Recipe", null)
                        .WithMany("Lists")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Recetarion.Models.Follow", b =>
                {
                    b.HasOne("Recetarion.Models.User", "Followee")
                        .WithMany()
                        .HasForeignKey("FolloweeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Recetarion.Models.User", "Follower")
                        .WithMany()
                        .HasForeignKey("FollowerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Followee");

                    b.Navigation("Follower");
                });

            modelBuilder.Entity("Recetarion.Models.Group", b =>
                {
                    b.HasOne("Recetarion.Models.UserPermission", null)
                        .WithMany("Groups")
                        .HasForeignKey("UserPermissionUserRolesId", "UserPermissionAction");
                });

            modelBuilder.Entity("Recetarion.Models.GroupPermission", b =>
                {
                    b.HasOne("Recetarion.Models.GroupRole", null)
                        .WithMany("Permissions")
                        .HasForeignKey("GroupRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Recetarion.Models.GroupRole", b =>
                {
                    b.HasOne("Recetarion.Models.Group", null)
                        .WithMany("Roles")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Recetarion.Models.Image", b =>
                {
                    b.HasOne("Recetarion.Models.Publication", null)
                        .WithMany("Images")
                        .HasForeignKey("PublicationId");
                });

            modelBuilder.Entity("Recetarion.Models.Ingredient", b =>
                {
                    b.HasOne("Recetarion.Models.UserPermission", null)
                        .WithMany("Ingredients")
                        .HasForeignKey("UserPermissionUserRolesId", "UserPermissionAction");
                });

            modelBuilder.Entity("Recetarion.Models.LikeIngredient", b =>
                {
                    b.HasOne("Recetarion.Models.Ingredient", null)
                        .WithMany("Likes")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Recetarion.Models.User", null)
                        .WithMany("LikeIngredients")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Recetarion.Models.UserPermission", null)
                        .WithMany("LikeIngredients")
                        .HasForeignKey("UserPermissionUserRolesId", "UserPermissionAction");
                });

            modelBuilder.Entity("Recetarion.Models.LikePublication", b =>
                {
                    b.HasOne("Recetarion.Models.Publication", null)
                        .WithMany("Likes")
                        .HasForeignKey("PublicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Recetarion.Models.User", null)
                        .WithMany("LikePublications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Recetarion.Models.UserPermission", null)
                        .WithMany("LikePublications")
                        .HasForeignKey("UserPermissionUserRolesId", "UserPermissionAction");
                });

            modelBuilder.Entity("Recetarion.Models.Publication", b =>
                {
                    b.HasOne("Recetarion.Models.UserPermission", null)
                        .WithMany("Publications")
                        .HasForeignKey("UserPermissionUserRolesId", "UserPermissionAction");
                });

            modelBuilder.Entity("Recetarion.Models.Recipe", b =>
                {
                    b.HasOne("Recetarion.Models.CustomList", null)
                        .WithMany("Recipes")
                        .HasForeignKey("CustomListId");
                });

            modelBuilder.Entity("Recetarion.Models.RecipeIngredient", b =>
                {
                    b.HasOne("Recetarion.Models.Ingredient", null)
                        .WithMany("RecipePivot")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Recetarion.Models.Recipe", null)
                        .WithMany("IngredientsQuantitys")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Recetarion.Models.Step", b =>
                {
                    b.HasOne("Recetarion.Models.Recipe", null)
                        .WithMany("Steps")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Recetarion.Models.Subscription", b =>
                {
                    b.HasOne("Recetarion.Models.Group", null)
                        .WithMany("Subscriptions")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Recetarion.Models.User", null)
                        .WithMany("Subscriptions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Recetarion.Models.UserPermission", null)
                        .WithMany("Subscriptions")
                        .HasForeignKey("UserPermissionUserRolesId", "UserPermissionAction");
                });

            modelBuilder.Entity("Recetarion.Models.User", b =>
                {
                    b.HasOne("Recetarion.Models.Ingredient", null)
                        .WithMany("Users")
                        .HasForeignKey("IngredientId");

                    b.HasOne("Recetarion.Models.UserRole", null)
                        .WithMany("Users")
                        .HasForeignKey("UserRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Recetarion.Models.UserPermission", b =>
                {
                    b.HasOne("Recetarion.Models.UserRole", null)
                        .WithMany("Permissions")
                        .HasForeignKey("UserRoleId");
                });

            modelBuilder.Entity("Recetarion.Models.CustomList", b =>
                {
                    b.Navigation("Recipes");

                    b.Navigation("RecipesPivot");
                });

            modelBuilder.Entity("Recetarion.Models.Group", b =>
                {
                    b.Navigation("Roles");

                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("Recetarion.Models.GroupRole", b =>
                {
                    b.Navigation("Permissions");
                });

            modelBuilder.Entity("Recetarion.Models.Ingredient", b =>
                {
                    b.Navigation("Likes");

                    b.Navigation("RecipePivot");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Recetarion.Models.Publication", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Images");

                    b.Navigation("Likes");
                });

            modelBuilder.Entity("Recetarion.Models.Recipe", b =>
                {
                    b.Navigation("Critics");

                    b.Navigation("IngredientsQuantitys");

                    b.Navigation("Lists");

                    b.Navigation("Steps");
                });

            modelBuilder.Entity("Recetarion.Models.User", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("LikeIngredients");

                    b.Navigation("LikePublications");

                    b.Navigation("Lists");

                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("Recetarion.Models.UserPermission", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Groups");

                    b.Navigation("Ingredients");

                    b.Navigation("LikeIngredients");

                    b.Navigation("LikePublications");

                    b.Navigation("Lists");

                    b.Navigation("Publications");

                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("Recetarion.Models.UserRole", b =>
                {
                    b.Navigation("Permissions");

                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
